pystac_monty/sources/gdacs.py

- Fix create impact item for gdacs by checking sendai name as 'affected'

Fix create impact item for gdacs.

---

pystac_monty/sources/glide.py
tests/extensions/cassettes/test_gdacs/GDACSTest.test_transformer_0.yaml
tests/extensions/cassettes/test_gdacs/GDACSTest.test_transformer_1.yaml
tests/extensions/cassettes/test_glide/GlideTest.test_transformer_0.yaml
tests/extensions/cassettes/test_monty/MontyTest.test_validates_reference_event.yaml
tests/extensions/test_glide.py

Add Glide hazard 
Add event type prefix to the id
Need to update the glide hazard collection url

Add Glide hazard;

---

pystac_monty/sources/glide.py

- Fix glide transformation for empty data.

Fix flow of execution for glide glide-transformation

---

docs/docs/api/sources.md
docs/docs/api/sources/usgs.md
docs/mkdocs.yml
pyproject.toml
pystac_monty/sources/usgs.py
tests/extensions/cassettes/test_emdat/EMDATTest.test_transformer_0.yaml
tests/extensions/cassettes/test_gdacs/GDACSTest.test_transformer_0.yaml
tests/extensions/cassettes/test_gdacs/GDACSTest.test_transformer_1.yaml
tests/extensions/cassettes/test_glide/GlideTest.test_transformer_0.yaml
tests/extensions/cassettes/test_monty/MontyTest.test_validates_reference_event.yaml
tests/extensions/cassettes/test_usgs/USGSTest.test_transformer_0.yaml
tests/extensions/test_usgs.py
uv.lock

Initial USGS implementation

---

pystac_monty/sources/idu.py

Remove whitespace

---

pystac_monty/sources/gdacs.py

Fix hazard code for gdacs.

---

pystac_monty/sources/glide.py

Add hazard_code func for glide.

---

pystac_monty/sources/gdacs.py
pystac_monty/sources/gidd.py

- Fix hazard code for mixed disaster in gidd.

Fix hazard code for mixed disaster in GIDD transformer.

---

pystac_monty/extension.py

- Add label for impact type for ifrc impact types.

Add potentially affected impact type for ifrc.

---

pystac_monty/sources/pdc.py

- Handle the episode number incase the value is alphabetic; Assign the episode_number to 0.

Handle the episode number incase the value is alphabetic; 

---

pystac_monty/sources/gidd.py

- Fix the GIDD event id prefix.

Fix the GIDD event id prefix

---

pystac_monty/HazardProfiles.csv

- Add hazard type in the hazard profiles csv.

Add the hazard type in the hazard profile mapping

---

pystac_monty/sources/ifrc_events.py

fix ifrc transformation.

---

pystac_monty/sources/pdc.py
tests/extensions/cassettes/test_desinventar/DesinventarTest.test_transformer_0_grd.yaml
tests/extensions/cassettes/test_ibtracs/IBTrACSTest.test_transformer_0_beryl.yaml
tests/extensions/cassettes/test_ibtracs/IBTrACSTest.test_transformer_1_multi_storm.yaml
tests/extensions/cassettes/test_ibtracs/IBTrACSTest.test_transformer_2_landfall.yaml
tests/extensions/cassettes/test_ibtracs/IBTrACSTest.test_transformer_3_North_Atlantic.yaml
tests/extensions/cassettes/test_monty/MontyTest.test_validates_reference_event.yaml

- pass data into pdc transformer rather than file path

Send data into pdc transformer rather than file path.

---

pystac_monty/sources/gfd.py
pystac_monty/validators/gfd.py

- Add partial success for GFD.

Apply partial success for gfd.

---

pystac_monty/sources/emdat.py
pystac_monty/sources/gdacs.py
pystac_monty/sources/ifrc_events.py

Removed the validation layer in source

Remove validation in source

---

docs/docs/api/sources/gdacs.md
pystac_monty/sources/gdacs.py
tests/extensions/cassettes/test_gdacs/GDACSTest.test_transformer_0.yaml
tests/extensions/test_gdacs.py

I had to refactor GDACS and still not complete but now producing correct data.

refactored gdacs

---

pystac_monty/sources/ifrc_events.py
pystac_monty/validators/ifrc.py
tests/extensions/cassettes/test_ifrc_events/IfrcEventsTest.test_transformer_0.yaml

- Add partial success for ifrc events.
- Fix typing issue.
- Add functionality to generate transformation summary.

Add partial success for ifrc events.

---

pystac_monty/geocoding.py
pystac_monty/sources/usgs.py
pystac_monty/validators/usgs.py
tests/extensions/test_usgs.py

- Add partial success for USGS source
- Add validator for USGS

Add partial success for USGS and validator

---

pystac_monty/sources/pdc.py
pystac_monty/validators/pdc.py
tests/extensions/cassettes/test_gdacs/GDACSTest.test_transformer_0.yaml
tests/extensions/cassettes/test_pdc/PDCTest.test_transformer_0.yaml

- Partial Success
- Validator in pdc

Partial Success and validator in pdc

---

pystac_monty/sources/glide.py
pystac_monty/validators/glide.py

- change type of magnitude of glide data to str.

change type of magnitude of glide data to str.

---

pystac_monty/sources/emdat.py

fix item title for emdat.

---

pystac_monty/validators/usgs.py

- Update validator in usgs(coordinate)

Update validator in usgs(coordinate)

---

pystac_monty/sources/gdacs.py
pystac_monty/validators/gdacs_events.py
pystac_monty/validators/gdacs_geometry.py
tests/extensions/test_gdacs.py

- Add the GDACS partial success
- Update the test cases

Fix and refactor to add the partial success

---

pystac_monty/sources/gdacs.py

- Fix issue with sendai indicator injured.

Fix issue with sendai indicator injured.

---

pystac_monty/sources/gdacs.py

Fix impact type for gdacs.

---

pystac_monty/sources/emdat.py
pystac_monty/validators/em_dat.py
tests/extensions/test_emdat.py

- Ignore the nan validation for admin_units

Fix the validation check for emdat source (admin_units)

---

pystac_monty/geocoding.py
pystac_monty/sources/ifrc_events.py
pystac_monty/validators/ifrc.py

- Update the validation for field countries
- Check for countries field to tackle empty list conditions
- Update the mock geocoder with the geometries for few countries.

Fix the validation and get geometry from the iso or country name;

---

notebooks/stac_helpers.py
pystac_monty/geocoding.py
pystac_monty/hazard_profiles.py
pystac_monty/sources/emdat.py
pystac_monty/sources/gdacs.py
pystac_monty/sources/gidd.py
pystac_monty/sources/glide.py
pystac_monty/sources/idu.py
pystac_monty/sources/pdc.py
pystac_monty/sources/usgs.py
pystac_monty/validators/em_dat.py
pystac_monty/validators/gdacs_events.py
pystac_monty/validators/glide.py
pystac_monty/validators/ifrc.py
pystac_monty/validators/pdc.py
pystac_monty/validators/usgs.py
tests/extensions/test_hazard_profiles_full.py

- Apply lint and code formatter using pre-commit configs.

Apply Lint and code formatter

---

pystac_monty/sources/common.py
pystac_monty/sources/emdat.py
tests/extensions/cassettes/test_emdat/EMDATTest.test_transformer_0.yaml
tests/extensions/test_emdat.py

- Accept file as transformer input for EMDAT.

add file streaming for emdat.

---

pystac_monty/sources/emdat.py
tests/extensions/cassettes/test_emdat/EMDATTest.test_transformer_0.yaml
tests/extensions/cassettes/test_gdacs/GDACSTest.test_transformer_0.yaml
tests/extensions/test_emdat.py

- add MontyDataSourceVe
-  add file streaming
- Feature/add test case emdat file input transformer

Emdat: File streaming using ijson.

---

pystac_monty/sources/idu.py
pystac_monty/sources/utils.py
tests/extensions/test_idu.py

- Handle sorting of the file using jq tool
- Handle file streaming using ijson

Handle file streaming for IDU source

---

pystac_monty/sources/emdat.py
tests/extensions/cassettes/test_emdat/EMDATTest.test_transformer_0.yaml
tests/extensions/cassettes/test_emdat/EMDATTest.test_transformer_with_file_data_0.yaml
tests/extensions/cassettes/test_emdat/EMDATTest.test_transformer_with_json_data_0.yaml
tests/extensions/test_emdat.py

- Support both file and data as transformation input for EMDAT.

EMDAT: support both file and data for emdat transformation.

---

pystac_monty/sources/gfd.py
tests/extensions/cassettes/test_gfd/GFDTest.test_transformer_0.yaml
tests/extensions/cassettes/test_gfd/GFDTest.test_transformer_from_file_0.yaml
tests/extensions/test_gfd.py

Update the GFD Data source with the updated schema

Update the GFD source with the file/memory schema class

---

pystac_monty/sources/ibtracs.py
tests/extensions/cassettes/test_ibtracs/IBTrACSTest.test_transformer_0_beryl.yaml
tests/extensions/cassettes/test_ibtracs/IBTrACSTest.test_transformer_1_multi_storm.yaml
tests/extensions/cassettes/test_ibtracs/IBTrACSTest.test_transformer_2_landfall.yaml
tests/extensions/cassettes/test_ibtracs/IBTrACSTest.test_transformer_3_North_Atlantic.yaml
tests/extensions/test_ibtracs.py

Add file streaming for ibtracs
